### ISSUE TITLE
App class

### ISSUE THREAD

**Issue by zoyaio** [SahilGhosalkar/Love_Hopital#25]
Will provide the whole interface for a User to update information about themselves and their partner (later, will be multiple partners) 

Will give User a menu of options to interact with the relationship: 

1. update relationship with a Flag --> see below
2. See relationship status --> prints out RelationshipBar
3. End relationship --> generate breakup text with all flags, do something with Relationship history or something idk

If User selects (1), update relationship with Flag, they will be presented with the following options:

1. Search through Index of all Flags --> will return a list of flags that match the user's search query
2. Update with Flag ID right now --> will print out a list of ALL flags, with their IDs and then the user will be able to input a list of all the flags that their partner has done

**Comment by SahilGhosalkar** [comment]
moved to 28
