### ISSUE TITLE
Import list of existing Flags from file input

### ISSUE THREAD

**Issue by zoyaio** [SahilGhosalkar/Love_Hopital#29]
basically the User has the option to "import all existing Flags" in our cataolgoue which will be stored in some sort of text file

Tasks
* create a text file + structure to store each flag and its corresponding information (like each row = a new Flag, all Flag information will be stored as Color, Name, Description) or something
* Use File readers and parsers and Scanner class to read input from File and add each of the Flags stored in that database into the FlagIndex class 
* Add an option in the User class or App class to call this method to import everything from that file

**Comment by zoyaio** [comment]
i'm gonna do part of it so i can make better test cases for issue 17 but can someone do the user interface part later B)))))

**Comment by SahilGhosalkar** [comment]
yeah ill do user interface

**Comment by SahilGhosalkar** [comment]
nvm u alr did it

**Comment by SahilGhosalkar** [comment]
i will create the app class in another issue (25) so we can finish last step

**Comment by SahilGhosalkar** [comment]
im putting the current version of Flag index into main so I can keep working on  App class

**Comment by SahilGhosalkar** [comment]
oops i forgot to say i did this
