### ISSUE TITLE
FlagIndex changes

### ISSUE THREAD

**Issue by zoyaio** [SahilGhosalkar/Love_Hopital#32]
* create a method that will just add a Flag and automatically generate an ID (basically addFlag but without the ID parameter, will instead RETURN the ID generated) 
* add a toString method

**Comment by zoyaio** [comment]
@kelley-zha perchance hahahhahahha

**Comment by SahilGhosalkar** [comment]
ill do it

**Comment by SahilGhosalkar** [comment]
this was already done
